### ISSUE TITLE
String found where operator expected at Makefile.PL line 5, near "readme_from 'lib/RDF/KV.pm'"

### ISSUE THREAD

**Issue by szabgab** [doriantaylor/p5-rdf-kv#2]
I cloned the repo and tried to run the tests, but got this error:

```
$ perl Makefile.PL 
include /home/gabor/os/p5-rdf-kv/inc/Module/Install.pm
String found where operator expected at Makefile.PL line 5, near "readme_from 'lib/RDF/KV.pm'"
	(Do you need to predeclare readme_from?)
syntax error at Makefile.PL line 5, near "readme_from 'lib/RDF/KV.pm'"
Execution of Makefile.PL aborted due to compilation errors.
```

```
perl -v

This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-gnu-thread-multi
(with 57 registered patches, see perl -V for more detail)
```

```
mversion inc::Module::Install
1.19
```

**Comment by doriantaylor** [comment]
It needs [Module::Install::ReadmeFromPod](https://metacpan.org/pod/Module::Install::ReadmeFromPod) which of course you can't specify as a dependency because that is the place you'd do it.

Actually come to think of it I moved to a `cpanfile` recently so maybe I can.

Note before you get comfortable that this whole thing is gonna get turfed Any Day Now™ and moved to Ruby.

**Comment by doriantaylor** [comment]
oh wait I thought I was looking at an issue in [App::IBIS](https://github.com/doriantaylor/p5-app-ibis). (This has already been [ported to Ruby](/doriantaylor/rb-rdf-kv).)

**Comment by szabgab** [comment]
Thanks. I've update the CI and the pull-request.

**Comment by szabgab** [comment]
Oh and I think it is worth adding the CI even you plan to stop maintaining the Perl implementation. Someone might come along and will want to continue it and then it is good that there is a CI already in place.
